[build]
  # Ignore builds if changes are NOT in these specific files/folders
  # Exit code 0 = Ignore build (Cancel)
  # Exit code 1 = Proceed with build
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- index.html main.js main.css netlify/ sessions.json unified_courses.json package.json"

[functions]
  # Ensure the data file is bundled with the function
  included_files = ["sessions.json"]